### ISSUE TITLE
Overflow in Mobile View

### ISSUE THREAD

**Issue by grixxxx** [calagkit100/Chibugan#1]
overflow in mobile view.  and subtitle  is too small

![image](https://user-images.githubusercontent.com/110141187/204232393-34f1d839-c139-4b95-bc64-6a58388b96b2.png)

![image](https://user-images.githubusercontent.com/110141187/204232675-741978fc-8693-4728-87fc-9347307c9bb5.png)

**Comment by calagkit100** [comment]
Thank you Delmer!
